name: Run SOAtest Action

on:
  workflow_dispatch:

jobs:
  build:
    name: Test Action
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run local action
        uses: Parasoft/run-soatest-action@master
        with:
          installDir: D:\Parasoft_SOAtest_Virtualize_2024.1
          soatestWorkspace: ${{ github.workspace }}/soatest
          testConfig: user://Example Configuration
          settings: soatest/license.properties
          resource: TestAssets
          report: ${{ github.workspace }}/soatest/reports
          reportFormat: xml,html
          convertReportToXUnit: true

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: ${{ github.workspace }}/soatest/reports

  publish:
    name: Publish Reports
    needs: [build]
    permissions:
        checks: write
        pull-requests: write
        contents: read
        issues: read
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: reports

      - name: Upload results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: |
            ${{ github.workspace }}/soatest/reports/report-xunit.xml
            ${{ github.workspace }}/soatest/reports/report.xml
            ${{ github.workspace }}/soatest/reports/report_dev1.html
            ${{ github.workspace }}/soatest/reports/report.html
