name: test-parabank-soatest

on: 
 # push:
    #branches: [ main ]
    # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
permissions:
   checks: write
   pull-requests: write
   contents: read
   issues: read
jobs:
  test-soatest:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: run-soatest-action
      uses: parasoft/run-soatest-action@1.0.0
      with:
        installDir: ‪D:\Parasoft_SOAtest_Virtualize_2024.1
        soatestWorkspace:  ${{ github.workspace }}/soatest
        testConfig: builtin://Example Configuration
        settings: soatest/license.properties
        report: soatest/reports
        reportFormat: xml
        environment: ../../../test-env
        convertReportToXUnit: TRUE
               
